### ISSUE TITLE
dnf-json fails when deploying master to Fedora 31

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#278] opened 2020-03-04 13:51 UTC
Steps to reproduce:
 1. Try to insert a package into a blueprint in our "auto-deploy" instance

Result:
```
-- The job identifier is 9124.
Mar 04 13:46:35 composer-fedora31 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-timedated comm="systemd" exe="/usr/lib/systemd/systemd" host>
Mar 04 13:46:38 composer-fedora31 PackageKit[172230]: get-updates transaction /22_acbabaab from uid 0 finished with success after 2747ms
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]: Traceback (most recent call last):
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]:   File "dnf-json", line 122, in <module>
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]:     base.install_specs(arguments["package-specs"], exclude=arguments.get("exclude-specs", []))
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]:   File "/usr/lib/python3.7/site-packages/dnf/base.py", line 1838, in install_specs
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]:     install_specs, exclude_specs = self._categorize_specs(install, exclude)
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]:   File "/usr/lib/python3.7/site-packages/dnf/base.py", line 1775, in _categorize_specs
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]:     _parse_specs(install_specs, install)
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]:   File "/usr/lib/python3.7/site-packages/dnf/util.py", line 70, in _parse_specs
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]:     for value in values:
Mar 04 13:46:50 composer-fedora31 osbuild-composer[172059]: TypeError: 'NoneType' object is not iterable
Mar 04 13:47:05 composer-fedora31 systemd[1]: systemd-hostnamed.service: Succeeded.
-- Subject: Unit succeeded

```

**Comment by gicmo** [comment] 2020-03-04 13:56
Was this not fixed by https://github.com/osbuild/osbuild-composer/pull/260 ?

**Comment by msehnout** [comment] 2020-03-04 15:20
I thought it would deploy the latest commit from the master branch. Isn't that the case @major ?

**Comment by larskarlitski** [comment] 2020-03-06 08:06
> I thought it would deploy the latest commit from the master branch. Isn't that the case @major ?

It does. I cannot reproduce on the latest deployment, which has `golang-github-osbuild-composer-7-1.20200306git23fe851.fc31.x86_64`.

I'm certain this is the problem that #260 fixed. Feel free to reopen if you see this bug again.

**Closed by larskarlitski** 2020-03-06 08:06 UTC
