### ISSUE TITLE
CI needs a consistent version of osbuild to use

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#830] opened 2020-07-08 19:19 UTC
CI currently uses the osbuild submodule in the main osbuild-composer repository to know which osbuild version to build and test. However, this submodule has not been updated for osbuild v18 and that's causing breakage due to missing python in RHEL 8.x.

We need to consistently get a useful version of osbuild in CI. Here are a few options:

1. Keep using the submodule and bump it forward when osbuild does a release.
2. Stop using the submodule and get the latest tag from osbuild's repository.
3. Stop using the submodule and use osbuild's master branch.

I like option 2 the best since it's a lot like 1 but there's no effort needed to update it.

**Comment by ondrejbudai** [comment] 2020-07-09 10:05
I would like to see two things:

1) CI always uses the latest released version of osbuild.
   Using the master branch should be fine but it doesn't represent how our current downstreams use our projects - they use exclusively the releases. Thus, I would prefer using them.

2) CI doesn't switch versions without our knowledge.
   In a dream world, nothing bad should happen, but in reality, something might break during the upgrade. Therefore, the change should always be tested by CI before it's merged into master.

This is the ideal workflow from my perspective: Once a new version of osbuild is released, bot opens a PR in osbuild-composer which bumps the osbuild version (it can be tracked as a submodule or just a text file with a version in it). Someone from the team must approve the change and merge it into master.

This workflow is basically the same as the cockpit team uses for bumping their dependencies. Also, cyborgs like things like this.

**Comment by teg** [comment] 2020-07-10 11:27
How about something like this:

 1. kill the submodule
 2. don't treat osbuild any different than any other dependency, but test against whatever has landed in our downstreams
 3. in an ideal world we would be able to pin all our dependencies, not only the osbuild one. Ideally by snapshoting the repos we test against, but alternatively by installing the dependencies into a test image and pinning that.

(markdown does not want to let me start the list with 0., very sad)

This would avoid problems where we update the osbuild we test against too soon, and then end up releasing osbuild-composer into a distro where the new osbuild has not landed yet (as happened once).

**Comment by major** [comment] 2020-07-10 18:35
@teg Ah, so you're suggesting we mock build only osbuild-composer and just take whatever osbuild exists inside the Fedora/RHEL repositories already? If so, I can get behind that.

**Comment by teg** [comment] 2020-07-10 18:37
Exactly :)

**Comment by major** [comment] 2020-07-10 18:38
@teg Sounds like a decent enough idea for me. Should we do the reverse in osbuild's CI?

**Comment by teg** [comment] 2020-07-10 18:42
Makes sense to me! I guess in fedora we ship the composer test package, so it'll "just work", right?

**Comment by major** [comment] 2020-07-10 19:18
We don't ship the `-tests` package, so we will need another option. https://koji.fedoraproject.org/koji/buildinfo?buildID=1538323

**Comment by teg** [comment] 2020-07-10 20:35
Hm, I have no good suggestions off the top of my head. But schutzbot will have built the `-tests` package for a given release, and it is stuffed in S3, so one option could be to add the right repo for the matching `-tests` package to whatever `osbuild-composer` we are installing. Though that does not make me feel warm and fuzzy inside. We'll have the same conundrum in gating, I guess, I have not looked at how it is solved there.

**Comment by ondrejbudai** [comment] 2020-07-13 09:27
While I like @teg suggestions, I see some issues:

1) It works with Fedora because we can ship there continuously. However, how would it work with RHEL? We cannot deliver continuously there.
2) With our current method, we can ship a new feature spanning our whole stack in 3 weeks. (1st week to osbuild, 2nd week to osbuild-composer, 3rd week to cockpit-composer). With your suggestion, we can merge new features in osbuild-composer one week after osbuild release (the default bodhi stable-by-time interval). However, this is usually right before the new osbuild-composer release. So, we would probably need to wait for one more osbuild-composer release to get the new features in. This effectively means that the new feature can be now integrated in 6 weeks. Is that acceptable?

**Comment by teg** [comment] 2020-07-13 11:29
Good points @ondrejbudai 
1. For RHEL I see three scenarios
  - We are able to push into nightlies or something like it (Cent OS Stream? I believe this is the workflow we can always rely on for RHEL 9): This is straight-forward, treat nightlies as we treat Fedora and do as we did until the beta freeze.
   - We cannot do this because RHEL is frozen, and we will no longer release feature releases into it: if we won't release, then don't test against it. Do nothing.
  - We will not release into RHEL, but we will still be running the software on RHEL from a (our) third-party repo. This will be the cause for our services. In this case, release into our own repo and treat this as if it was the regular downstream.
2. I think with improved CI (compared to a regular Fedora package), and ideally the same tests running in Fedora gating, we can and should (if technically possible) reduce the time spent in testing (I would say to 0).

**Comment by atodorov** [comment] 2020-10-13 08:52
Solved by https://github.com/osbuild/osbuild-composer/pull/966 ?

**Comment by ondrejbudai** [comment] 2020-12-16 11:10
Done!

**Closed by ondrejbudai** 2020-12-16 11:10 UTC
Labels: ci-reliability
