### ISSUE TITLE
Unable to start osbuild-composer on RHEL-8.4 GA

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#1576] opened 2021-07-21 10:33 UTC
**Describe the bug**
Unable to start osbuild-composer on RHEL-8.4 GA. `2021/07/21 06:00:18 Error initializing weldr API: loaded repository definitions don't contain any for the host distro/arch: there are no repositories for distribution 'rhel-84' and architecture 'x86_64'`

**Environment**
 * OS version: RHEL-8.4 GA
 * osbuild-composer version: built from source while on 583bfc0b4a822f7853323f25022cfb059e13b50f in main

**To Reproduce**
`systemctl start osbuild-composer.socket`

**Expected behavior**
osbuild-composer.socket and service starts

**Comment by thozza** [comment] 2021-07-21 10:47
From a brief look, I think that the problematic part is https://github.com/osbuild/osbuild-composer/blob/583bfc0b4a822f7853323f25022cfb059e13b50f/internal/weldr/api.go#L144-L151
Specifically that Weldr tries to get the host distro name using `distro.GetHostDistroName()`, which does not "mangle" the distro name and for minor versions `>= 4` it always returns the name `rhel_xy` instead of `rhel_x`. Then the code tries to get the distro from the distro registry using the mame, but the issue is that in RPMs shipped in RHEL, we don't include repositories for specific minor RHEL versions.

I do believe that the fix here is to call `distroregistry.Registry.FromHost()` method to directly get the host distro definition instance:
https://github.com/osbuild/osbuild-composer/blob/583bfc0b4a822f7853323f25022cfb059e13b50f/internal/distroregistry/distroregistry.go#L128

The core of the problem is that this part
https://github.com/osbuild/osbuild-composer/pull/1427/files#diff-fe743ec28260b37c624410f3a34f54bd498871b621dc90f3745d45803c1c089aL79-L98
was not correctly moved to Weldr and uses "not mangled" name to get the host distro
https://github.com/osbuild/osbuild-composer/pull/1427/files#diff-3e98e022524e7eaf03f93b64cf38427d2f97b96259e039647967bb5db6f18429R144-R154

**Comment by bcl** [comment] 2021-07-21 15:53
Ahh, right, that seems to have gotten lost/confused when I rebased it on top of the distroregistry change (in a previous iteration of the PR there was a new mangleName function which handled that).

**Comment by bcl** [comment] 2021-07-21 18:52
@jrusz I am unable to get current main branches of osbuild/osbuild-composer running on 8.4 so I'm not 100% sure this fixes things. Also not sure how to add testing for this, if it's even possible?

**Comment by bcl** [comment] 2021-07-21 21:28
Ok, so the problem isn't that the mangling isn't happening it is that it stops for 8.4 and there is no 8.4 repo file.

I tried using distroregistry, but doing that then mangles the name into one that isn't in the registry so the schutzbot tests for things like centos-stream-8 and rhel-8-beta all fail because those are unknown distros.

So I think this needs to actually be fixed by getting rid of this mangling nonsense and actually having repos for the distros, or aliases as #1577 suggests.

In the short term this would be fixed by adding rhel-84.repo

**Comment by bcl** [comment] 2021-07-22 15:19
Short term fix merged in #1579

**Comment by teg** [comment] 2021-08-24 08:16
This seems fixed to me. Please reopen if still a problem.

**Closed by teg** 2021-08-24 08:16 UTC
Labels: bug
