### ISSUE TITLE
Fedora IoT Rawhide compose is failing with  "Received empty package specs" (from compose-status.json)

### ISSUE THREAD

**Issue by paulwhalen** [osbuild/osbuild-composer#3125] opened 2022-11-09 16:01 UTC
**Describe the bug**
Fedora Rawhide compose is failing with the error (from compose-status.json):

reason  "Received empty package specs"
reason  "Manifest dependency failed"

Koji Task:
https://koji.fedoraproject.org/koji/taskinfo?taskID=93976262

Full compose logs:
https://kojipkgs.fedoraproject.org/compose/iot/Fedora-IoT-38-20221108.0/

**Environment**
 *  Fedora Koji
 
**To Reproduce**

To manually reproduce the error:
koji osbuild-image Fedora-IoT 38 fedora-38 f38-candidate x86_64 --repo='https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20221109.n.0/compose/Everything/x86_64/os/' --ostree-url='http://kojipkgs.fedoraproject.org/compose/iot/repo/' --ostree-ref='fedora/devel/$arch/iot' --image-type iot-installer --release 38.20221109.1 --skip-tag

https://koji.fedoraproject.org/koji/taskinfo?taskID=93978382

**Expected behavior**
Completed task in koji.

**Comment by ondrejbudai** [comment] 2022-11-09 16:04
I believe this should be fixed by https://github.com/osbuild/osbuild-composer/pull/3067

**Comment by paulwhalen** [comment] 2022-11-09 16:47
In the past we saw mention of the package in particular:

"DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:\nmissing packages: sil-scheherazade-fonts"

I believe I fixed the [packaging bug](https://src.fedoraproject.org/rpms/sil-scheherazade-fonts/pull-request/2#request_diff) with "sil-scheherazade-fonts", so it should now work without #3067

**Comment by AdamWill** [comment] 2022-11-09 18:10
That concerns me, though. Why would sil-scheherazade-fonts be pulled in at all?

I corrected the comps entry to be "sil-scheherazade-new-fonts" last week, but that entry is "optional". No image build-type process should be pulling in packages marked as "optional" in comps, that is not how yum or dnf behave and it is not what comps maintainers expect. It would cause a huge amount of packages to be included in images which should not.

**Comment by ondrejbudai** [comment] 2022-11-10 16:50
The failure is more weird than I thought so, I'm double-checking everything.

**Comment by nullr0ute** [comment] 2022-11-11 12:48
> I have no experience with Fedora images, but in RHEL, when a kickstart used for images specified a comps group in the packages list, all optional members of that group get pulled in automatically. One had to explicitly exclude unwanted optional packages (e.g. a lot of firmware packages). osbuild-composer behaves the same way when building images WRT package installation, as DNF does when you use Anaconda for building images - it by default installs weak dependencies (at least from what I can tell from RHEL side).
> 
> Are you really sure that optional package group members were previously not installed into images if they were not explicitly excluded? It was never the case for RHEL images AFAICT... man_shrugging

Are you sure you're not confusing dnf weak dependencies by default in RHEL and not in Fedora as opposed to comps optional?

**Comment by ondrejbudai** [comment] 2022-11-11 13:44
I found the root cause and proposed a workaround (until #3120 lands and we can fix it properly) in https://github.com/osbuild/osbuild-composer/pull/3132.

Basically: a recent change in which we handle ostree references in the service broke Fedora IoT installer.

**Comment by thozza** [comment] 2022-11-11 15:43
> Are you sure you're not confusing dnf weak dependencies by default in RHEL and not in Fedora as opposed to comps optional?

I was not, but I was probably fooled in the past by the fact that optional packages in a comps group were also weak dependencies of some packages that are mandatory in that group, thus excluding weak dependencies made it look as if the wetting whether to install them affected also if optional packages from a comps group get installed.

Looking at the `dnf.conf` man page, I can see that weak dependencies and group package types installed are two different settings.

Nevertheless osbuild-composer's default behavior WRT depsolving is always the same as DNF's default behavior (by that I don't mean what is in the system's `dnf.conf`, but what DNF uses if no explicit configuration is provided. In reality this means that weak dependencies of packages specified in the base image package set are installed by default. We are explicitly turning off the installation of weak dependencies for user requested packages (this is longer story). As for the group package types, DNF defaults to installing `default` and `mandatory` packages from a group. AFAICT, osbuild-composer is not changing the DNF configuration in this regard.

**Closed** 2022-11-11 17:39 UTC

**Comment by thozza** [comment] 2022-11-14 15:25
> We seem to still be hitting this, but the errors now include:
> 
> reason "Fault(1000): Build is already reserved"
> 
> Task: https://koji.fedoraproject.org/koji/taskinfo?taskID=94166469 Compose logs: https://kojipkgs.fedoraproject.org/compose/iot/Fedora-IoT-38-20221114.0/

From the Koji task, it looks as the image was built successfully, but the tagging failed because of the build being in an incorrect state for building. A further investigation would be needed, but this is a different issue than what you reported in this bug report. It may be an issue in our integration with Koji, hard to tell from the first glance.

The `Fault(1000): Build is already reserved` is caused by using the same image NVR when submitting the build. Just bump the release (e.g. the last number after the dot).

**Comment by nullr0ute** [comment] 2022-11-14 15:46
> The `Fault(1000): Build is already reserved` is caused by using the same image NVR when submitting the build. Just bump the release (e.g. the last number after the dot).

It was bumped as it was a new day

**Comment by paulwhalen** [comment] 2022-11-14 20:18
Renamed the iot-installer to match what we used before, no longer seeing "Fault(1000): Build is already reserved", but we're still hitting the same errors:

Koji Task: https://koji.fedoraproject.org/koji/taskinfo?taskID=94176634

**Comment by thozza** [comment] 2022-11-15 08:21
I checked and the change was not yet deployed in the Image Builder prod Service (the currently deployer commit is `626530818d4b39839a49b6477b16ffb9e2c0d6fb`)... @ondrejbudai do you have some ETA when this will be fixed in the Service?

**Comment by ondrejbudai** [comment] 2022-11-15 10:12
Should be live in ~5 minutes.
