### ISSUE TITLE
Generating test case for rhel-84-aarch64-rhel-edge-commit - FAIL

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#1812] opened 2021-09-21 12:33 UTC
I tried to generate test cases for RHEL-8.4 and came across this failure:
```
2021-09-21 14:15:43,438 [ERROR] - aarch64-Runner: Generating test case for rhel-84-aarch64-rhel-edge-commit - FAIL
retcode: 1
stdout: generating test case for rhel-edge-commit
generating test case for rhel-edge-commit-rt

stderr: usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file pathname...
usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file -f filename
usage:  setfiles -s [-diIDlmnpqvFW] spec_file
usage:  setfiles -c policyfile spec_file
ostree config get core.mode --repo=/var/tmp/tmpyedn13uc/root/repo
ostree refs --repo=/var/tmp/tmpyedn13uc/root/repo
ostree rev-parse rhel/8/aarch64/edge --repo=/var/tmp/tmpyedn13uc/root/repo
ostree checkout --force-copy 3f588a26259cc0fa5e28a9cca7a534340fc5b8b0f8bf6899c35c600f050383ea /var/tmp/tmp8in9qfw8/tree --repo=/var/tmp/tmpyedn13uc/root/repo
No match for argument: kernel-rt
panic: Could not depsolve: DNF error occured: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: kernel-rt

goroutine 1 [running]:
main.main()
        /root/tmp.TGWKyC1DP7/sources/cmd/osbuild-pipeline/main.go:127 +0x1088
exit status 2
```
It seems that `kernel-rt` for aarch64 does not exist in any repository.

**Comment by ondrejbudai** [comment] 2021-09-21 12:40
This is a duplicate of #1478.

**Closed by ondrejbudai** 2021-09-21 12:40 UTC
