### ISSUE TITLE
Failing test: fedora_32-x86_64-fedora_iot_commit-boot

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#843] opened 2020-07-09 20:57 UTC
The Fedora 32 `fedora_iot_commit` test is failing (it was just added to CI):

```
[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
setfiles: Could not set context for /run/osbuild/tree/var/lib/containers:  Invalid argument
Traceback (most recent call last):
  File "/run/osbuild/lib/stages/org.osbuild.selinux", line 61, in <module>
    r = main(args["tree"], args["options"])
  File "/run/osbuild/lib/stages/org.osbuild.selinux", line 52, in main
    subprocess.run(["setfiles", "-F", "-r", f"{tree}", f"{file_contexts}", f"{tree}"], check=True)
  File "/usr/lib64/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['setfiles', '-F', '-r', '/run/osbuild/tree', '/run/osbuild/tree/etc/selinux/targeted/contexts/files/file_contexts', '/run/osbuild/tree']' returned non-zero exit status 255.
```

Pipeline link: https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-841/4/pipeline/237
Test log: [fedora_32-x86_64-fedora_iot_commit-boot.json.log](https://github.com/osbuild/osbuild-composer/files/4899480/fedora_32-x86_64-fedora_iot_commit-boot.json.log)

**Comment by ondrejbudai** [comment] 2020-07-09 21:07
This is actually a duplicate of #798.

**Closed by ondrejbudai** 2020-07-09 21:07 UTC
Labels: bug, ci-reliability

**Comment by major** [comment] 2020-07-10 18:32
Thanks, @ondrejbudai
