### ISSUE TITLE
Install ostree image failed on RHEL 8.4

### ISSUE THREAD

**Issue by henrywang** [osbuild/osbuild-composer#1147] opened 2021-01-06 13:42 UTC
On RHEL 8.4, RHEL-Edge image is able to build without error. But it can't be installed and report `http://192.168.100.1/repo/summary.sig: [7] Couldn't connect to server (0)` error.
The http server works when report this error.
Can't find same issue on RHEL 8.3.1.

anaconda log:
```
Configuring storage
Creating disklabel on /dev/vda
Creating xfs on /dev/vda2
Creating xfs on /dev/vda1
..
Running pre-installation scripts
.
Running pre-installation tasks
...
Installing.
Starting pull of rhel/8/x86_64/edge from rhel-edge-commit
================================================================================
================================================================================
Error

   The following error occurred while installing.  This is a fatal error and
   installation will be aborted.

   Failed to pull from repository: g-io-error-quark: While fetching
   http://192.168.100.1/repo/summary.sig: [7] Couldn't connect to server (0)

Press ENTER to exit:
```

**Comment by atodorov** [comment] 2021-01-12 14:10
@henrywang can you tell us more about your environment? The same test job in CI/latest commit seems to PASS. So what anaconda version, what osbuild-composer/8.4 version you are using to reproduce this ?

**Comment by henrywang** [comment] 2021-01-12 16:32
@atodorov, I run this test on PSI OpenStack VM with RHEL 8.4 nightly image. The repo (RHEL 8.4 system uses and osbuild-composer uses) is `http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.4.0/compose/BaseOS/x86_64/os/`.

anaconda version should be 33.16.4.4, because I use latest-RHEL-8.4.0 as boot image.
osbuild-composer: `20.1-1.el8`
ostree and rpm-ostree: `2020.7-1.el8`

**Comment by ondrejbudai** [comment] 2021-01-18 12:25
I updated the CI image to today's RHEL 8.4 compose and I still cannot reproduce this issue. Also, I found a newer run on the Jenkins instance you posted and it succeeded:

https://jenkins-cloudci-prod-virt-qe-3rd.cloud.paas.psi.redhat.com/job/rhel-edge/job/rhel840_edge_virt_x86_64/14/console

I'm afraid I cannot do much here without a reproducer.

**Comment by henrywang** [comment] 2021-01-18 14:01
@ondrejbudai, I found RHEL-Edge test got passed on my rhel nightly CI since RHEL-8.4.0-202101 15.n.0. I made comparison, the ostree, rpm-ostree, and anaconda are no different, but osbuild-composer got upgraded from 20.1 to 26.1. Is there any different between those two builds? Thanks.

**Comment by ondrejbudai** [comment] 2021-01-19 08:24
Yeah, this was a big rebase of osbuild-composer for 8.4.  There were a lot of changes but I'm not aware of any related to building ostree images.

Is it possible that this was a failure of the testing environment? I'm leaning towards closing this issue for now as we cannot reproduce it. Of course, we can reopen it any time if the issue appears again. Does it work for you?

**Comment by eat3xx** [comment] 2021-02-25 06:32
Hi, I reproduced this issue in my tes env, followings are my steps:

1. Install image builder and compose a RHEL edge commit image. 
2. Download and serve edge commit image over httpd at 192.168.100.1/ (on the same machine of step 1)
3. Sudo virt-install  --initrd-inject="${KS_FILE}" \
                              --extra-args="ks=file:/ks.cfg console=ttyS0,115200" \
                              --name="${IMAGE_KEY}"\
                              --disk path="${LIBVIRT_IMAGE_PATH}",format=qcow2 \
                              --ram 3072 \
                              --vcpus 2 \
                              --network network=integration,mac=34:49:22:B0:83:30 \
                              --os-type linux \
                              --os-variant ${OS_VARIANT} \
                              --location  ${REMOTE_BOOT_ISO_IN_NIGHTLY}\
                              --nographics \
                              --noautoconsole \
                              --wait=-1 \
                              --noreboot
4. After installation started, I connected to edge image vm console, I can see the installation started, but it failed with below error message:
      Installing.
      Starting pull of rhel/8/x86_64/edge from rhel-edge-commit
      ================================================================================
      ================================================================================
      Error
      
         The following error occurred while installing.  This is a fatal error and
         installation will be aborted.
         
         Failed to pull from repository: g-io-error-quark: While fetching
         http://192.168.100.1/repo/summary.sig: [7] Couldn't connect to server (0)
      
      Press ENTER to exit: 



Following is what I have tried:
1. turn off firewall on the machine where edge commit image is served over httpd(in this case its 192.168.100.1), I didn't see this error, installation completed without error.
2. turn on firewall again, and reproduced this error.

As turning off firewall is not recommended, so I did further investigation:
I turn on firewall, but allow access to httpd service. Run this command "firewall-cmd --add-service=http", and tested that I can access http 80 port,  then I tried again, but still see  this error. 

I am still trying to figure out how to configure firewall to make the installation success, does anyone know about this?

**Comment by eat3xx** [comment] 2021-02-25 07:26
@ondrejbudai , can you please take a look? 
I am not sure this is an osbuild-composer issue or edge commit image issue.
Maybe we need to suggest customer to add firewall rules before they start to install edge image.

**Comment by yih-redhat** [comment] 2021-03-05 08:20
Provide more information:

I have tried today again, and I am pretty sure this issue is caused by firewall, find more log details in following steps.

Steps:
1. Use image builder to build and download rhel-for-edge image, extracted to /var/www/html/ and served over httpd.
2. Create a disk to install rhel-for-edge image:  
    qemu-img create -f qcow2 /var/lib/libvirt/images/t1.qcow2 20G
3. Turn OFF firewall.
4. Install rhel-for-edge image.
[root@builder tmp]# virt-install  --initrd-inject=/tmp/tmp.HzO2vAqyhb/ks.cfg --extra-args="ks=file:/ks.cfg console=ttyS0,115200" --name=rhel-edge-commit --disk path=/var/lib/libvirt/images/t1.qcow2,format=qcow2 --ram 3072 --vcpus 2 --network network=integration,mac=34:49:22:B0:83:30 --os-type linux --os-variant rhel8-unknown --location /tmp/boot.iso --nographics --noautoconsole --wait=-1 --noreboot
5. Connect to console and watch the install progress.
Starting installer, one moment...
anaconda 33.16.4.8-1.el8 for Red Hat Enterprise Linux 8.4 (pre-release) started.
 * installation log files are stored in /tmp during the installation
 * shell is available on TTY2
 * if the graphical installation interface fails to start, try again with the
   inst.text bootoption to start text installation
 * when reporting a bug add logs from /tmp as separate text/plain attachments
08:06:56 Not asking for VNC because of an automated install
08:06:56 Not asking for VNC because text mode was explicitly asked for in kickstart
Starting automated install.
Saving storage configuration...
Checking storage configuration...

================================================================================

================================================================================
Installation

1) [x] Language settings                 2) [x] Time settings
       (English (United States))                (Etc/UTC timezone)
3) [x] Installation Destination          4) [x] Kdump
       (Automatic partitioning                  (Kdump is enabled)
       selected)
5) [x] Network configuration
       (Wired (enp1s0) connected)

================================================================================
================================================================================
Progress

.
Setting up the installation environment
Setting up org_fedora_oscap addon
Setting up com_redhat_kdump addon
..
Configuring storage
Creating disklabel on /dev/vda
Creating xfs on /dev/vda2
Creating xfs on /dev/vda1
..
Running pre-installation scripts
.
Running pre-installation tasks
...
Installing.
Starting pull of rhel/8/x86_64/edge from rhel-edge-commit
Receiving objects: 11% (2355/21294) 13.0 MB
Receiving objects: 14% (4287/30150) 21.4 MB
Receiving objects: 17% (5387/30150) 41.7 MB
Receiving objects: 21% (6567/30150) 65.3 MB
Receiving objects: 24% (7530/30150) 82.7 MB
Receiving objects: 28% (8685/30150) 102.6 MB
Receiving objects: 31% (9622/30150) 128.1 MB
Receiving objects: 34% (10405/30150) 149.0 MB
Receiving objects: 36% (10871/30150) 180.0 MB
Receiving objects: 38% (11581/30150) 192.7 MB
Receiving objects: 42% (12667/30150) 215.4 MB
Receiving objects: 44% (13567/30150) 241.7 MB
Receiving objects: 48% (14517/30150) 263.4 MB
Receiving objects: 51% (15461/30150) 284.6 MB
Receiving objects: 53% (16265/30150) 305.4 MB
Receiving objects: 56% (17090/30150) 320.1 MB
Receiving objects: 60% (18233/30150) 339.7 MB
Receiving objects: 63% (19181/30150) 357.0 MB
Receiving objects: 68% (20562/30150) 433.3 MB
Receiving objects: 70% (21207/30150) 463.7 MB
Receiving objects: 71% (21599/30150) 477.5 MB
Receiving objects: 75% (22663/30150) 498.6 MB
Receiving objects: 78% (23557/30150) 527.7 MB
Receiving objects: 80% (24385/30150) 554.1 MB
Receiving objects: 84% (25354/30150) 583.0 MB
Writing objects
Receiving objects: 88% (26672/30150) 621.6 MB
Receiving objects: 92% (27872/30150) 640.4 MB
Receiving objects: 95% (28888/30150) 657.9 MB
Receiving objects: 99% (30021/30150) 678.5 MB
Preparing deployment of rhel/8/x86_64/edge
Deployment starting: rhel/8/x86_64/edge

6. Installation succeeded.
7. Cleanup env, and turn ON firewall.
8. Repeat the steps  to install rhel-for-edge image, connect to console and watch install progress:
Starting installer, one moment...
anaconda 33.16.4.8-1.el8 for Red Hat Enterprise Linux 8.4 (pre-release) started.
 * installation log files are stored in /tmp during the installation
 * shell is available on TTY2
 * if the graphical installation interface fails to start, try again with the
   inst.text bootoption to start text installation
 * when reporting a bug add logs from /tmp as separate text/plain attachments
08:17:10 Not asking for VNC because of an automated install
08:17:10 Not asking for VNC because text mode was explicitly asked for in kickstart
Starting automated install.
Saving storage configuration...
Checking storage configuration...

================================================================================

================================================================================
Installation

1) [x] Language settings                 2) [x] Time settings
       (English (United States))                (Etc/UTC timezone)
3) [x] Installation Destination          4) [x] Kdump
       (Automatic partitioning                  (Kdump is enabled)
       selected)
5) [x] Network configuration
       (Wired (enp1s0) connected)

================================================================================
================================================================================
Progress

.
Setting up the installation environment
Setting up org_fedora_oscap addon
Setting up com_redhat_kdump addon
..
Configuring storage
Creating disklabel on /dev/vda
Creating xfs on /dev/vda2
Creating xfs on /dev/vda1
..
Running pre-installation scripts
.
Running pre-installation tasks
...
Installing.
Starting pull of rhel/8/x86_64/edge from rhel-edge-commit
================================================================================
================================================================================
Error

   The following error occurred while installing.  This is a fatal error and
   installation will be aborted.
   
   Failed to pull from repository: g-io-error-quark: While fetching
   http://192.168.100.1/repo/summary.sig: [7] Couldn't connect to server (0)

Press ENTER to exit: 
[anaconda]1:main* 2:shell  3:log  4:storage-log >Switch tab: Alt+Tab | Help: F1

**Comment by yih-redhat** [comment] 2021-03-05 09:29
Did more research:

Turn on firewall, and add http:80 to firewall. Still failed with same error.

[root@builder tmp.HzO2vAqyhb]# firewall-cmd --add-service=http
Warning: ALREADY_ENABLED: 'http' already in 'public'
success
[root@builder tmp.HzO2vAqyhb]# firewall-cmd --add-port=80/tcp --permanent 
Warning: ALREADY_ENABLED: 80:tcp
success
[root@builder tmp.HzO2vAqyhb]# firewall-cmd --list-services 
cockpit dhcpv6-client http https ssh
[root@builder tmp.HzO2vAqyhb]# firewall-cmd --list-ports 
80/tcp
[root@builder tmp.HzO2vAqyhb]# 

@gicmo Can you please help to take a look of this issue?

**Comment by yih-redhat** [comment] 2021-03-08 12:22
I reproduced this issue on 8.3.1, the behavior I observed is as same as 8.4  @gicmo

**Comment by yih-redhat** [comment] 2021-03-08 13:18
Here is the firewall settings to allow http access from outside.

[root@rhel-831-qcow2-ib edge]# firewall-cmd --get-active-zones
libvirt
  interfaces: integration
public
  interfaces: eth0
[root@rhel-831-qcow2-ib edge]# firewall-cmd --permanent --zone=libvirt --add-service=http
success
[root@rhel-831-qcow2-ib edge]# firewall-cmd --reload 
success
[root@rhel-831-qcow2-ib edge]# systemctl status firewalld.service 
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-03-08 07:11:46 EST; 1h 0min ago
     Docs: man:firewalld(1)

This  time, the firewall is active, and edge installation is successful. I also tried to allow http in zone: public, but does not work.

Here is the conclusion of this issue:
1. On the host machine where edge repo is served over httpd, if firewall is active, the edge installation will fail with error message "Couldn't connect to server (0)", if firewall is inactive, the edge installation will success.
2. Turn on firewall, and run command to allow http access from outside, the edge installation will success. But need to add http service in the right zone, otherwise edge installation will fail.
3. In my case, there are two active zones,  adding http service in the public zone does not work, but in zone libvirt, it works.

**Closed** 2021-03-09 11:09 UTC
