### ISSUE TITLE
Replace repo error?

### ISSUE THREAD

**Issue by zhangdexin** [osbuild/osbuild-composer#1417] opened 2021-05-24 03:37 UTC
When I replace my repo, My repo has "core" group, But when start compose the error happened:
```DNF error occured: MarkingErrors: Error occurred when marking packages for installation: Problems in request:```
```missing groups or modules: @Core```

**Comment by zhangdexin** [comment] 2021-05-24 07:06
/etc/os-release:
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"


rpm -qi osbuild-composer:
Name        : osbuild-composer
Version     : 28.4
Release     : 1.el8.0.1
Architecture: x86_64
Install Date: Wed May 19 07:16:20 2021
Group       : Unspecified
Size        : 17237
License     : ASL 2.0
Signature   : RSA/SHA256, Mon May  3 16:11:54 2021, Key ID 05b555b38483c65d
Source RPM  : osbuild-composer-28.4-1.el8.0.1.src.rpm
Build Date  : Mon May  3 16:04:14 2021
Build Host  : x86-01.mbox.centos.org
Relocations : (not relocatable)
Packager    : CentOS Buildsys <bugs@centos.org>
Vendor      : CentOS
URL         : https://github.com/osbuild/osbuild-composer
Summary     : An image building service based on osbuild
Description :

**Comment by msehnout** [comment] 2021-05-24 08:17
> 
> I not sure your configuration files for what??
> 
> @msehnout

You mentioned that you configured your own repo: `When I replace my repo, My repo has "core" group,`. Where did you configure it? Did you create a file in `/etc/osbuild-composer/repositories`? Or in `/etc/yum.repos.d/`?

**Comment by zhangdexin** [comment] 2021-05-24 08:19
I modify ```/usr/share/osbuild-composer/repositories/centos-stream-8.json```, turn my repo

**Comment by msehnout** [comment] 2021-05-24 08:21
Please share the content of this file as well. Also it is recommended to create configuration override in `/etc/osbuild-composer/repositories/` instead of modifying the system one in `/usr` (these are supposed to be static).

More info: https://www.osbuild.org/guides/user-guide/managing-repositories.html

**Comment by zhangdexin** [comment] 2021-05-24 08:56
I think it a bug. When i remove /var/cache/osbuild-composer, It work.

**Comment by msehnout** [comment] 2021-06-03 09:46
Unless we can get more information, I'll have to close this issue.

**Comment by ondrejbudai** [comment] 2021-06-03 12:30
I think this is a duplicate of #1434. I might be wrong though, feel free to reopen.

**Closed by ondrejbudai** 2021-06-03 12:30 UTC
